### ISSUE TITLE
Failed ot start on Portainer.

### ISSUE THREAD

**Issue by Marc-Harony** [joesturge/lazymc-docker-proxy#117]
Hi 👋🏻
I'm trying to run lazymc on my portainer stack but I cant start the container.

Here is the error I get:
```
 INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...

thread 'main' panicked at src/docker.rs:127:35:

called `Result::unwrap()` on an `Err` value: HyperLegacyError { err: hyper_util::client::legacy::Error(Connect, Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is the error when backtrace is set to full:

```
 INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...

thread 'main' panicked at src/docker.rs:127:35:

called `Result::unwrap()` on an `Err` value: HyperLegacyError { err: hyper_util::client::legacy::Error(Connect, Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }) }

stack backtrace:

   0:     0x7ff6257ad2e5 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h358afad87e02ca76

   1:     0x7ff6257f05bb - core::fmt::write::hb19b5b269a2fe458

   2:     0x7ff6257aa3cf - std::io::Write::write_fmt::he5a92676a45ef09d

   3:     0x7ff6257ae5d1 - std::panicking::default_hook::{{closure}}::h3bff550b24d93725

   4:     0x7ff6257ae2ac - std::panicking::default_hook::hd53b1b06d2b99687

   5:     0x7ff6257aec31 - std::panicking::rust_panic_with_hook::h9fdd87cddb2763da

   6:     0x7ff6257aea97 - std::panicking::begin_panic_handler::{{closure}}::h089783ab6b5cba45

   7:     0x7ff6257ad7a9 - std::sys::backtrace::__rust_end_short_backtrace::hed34776d77ef7922

   8:     0x7ff6257ae724 - rust_begin_unwind

   9:     0x7ff625529a83 - core::panicking::panic_fmt::h300583f35f37447a

  10:     0x7ff625529f56 - core::result::unwrap_failed::h83aef6e0d2ac917f

  11:     0x7ff625544474 - <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll::h2406317cd1cbd656

  12:     0x7ff625579e25 - tokio::runtime::context::runtime::enter_runtime::h99d60427f8817fcb

  13:     0x7ff6255982ba - tokio::runtime::runtime::Runtime::block_on::h54d663d8d16f8073

  14:     0x7ff6255b256d - lazymc_docker_proxy::docker::stop_all_containers::h2b9e7727fa987dab

  15:     0x7ff62555800e - lazymc_docker_proxy::main::hf15d152871f7455a

  16:     0x7ff625599923 - std::sys::backtrace::__rust_begin_short_backtrace::hafae9d3464739edb

  17:     0x7ff6255a5eb9 - std::rt::lang_start::{{closure}}::hf49b36fb5ace0c9b

  18:     0x7ff6257a2b97 - std::rt::lang_start_internal::h93b3b742566fb30c

  19:     0x7ff62555a355 - main
```

I'm using the example you provided [here](https://github.com/itzg/docker-minecraft-server/blob/master/docs/misc/examples.md#lazymc---put-your-minecraft-server-to-rest-when-idle).

Any help would be greatly appreciated :pray: !

Thanks :)

**Comment by Marc-Harony** [comment]
I solved my issue.
For any reason the .sock file for portainer is located in `/data/docker.sock`
